POST http://localhost:5183/auth/register
Content-Type: application/json

{
  "email": "ivan@mail.ru",
  "password": "12345678"
}

###
POST http://localhost:5183/auth/register
Content-Type: application/json

{
  "email": "ivan@mail.ru"
}
###
GET http://localhost:5183/auth/register

###
POST http://localhost:5183/auth/register

{
  "email": "ivan@mail.ru",
  "password": "12345678"
}
